name: comment-ops
on:
  issue_comment:
    types: [created]
permissions:
  contents: read
  issues: write
  pull-requests: write
  actions: read
concurrency:
  group: comment-ops-${{ github.event.issue.number }}
  cancel-in-progress: false
jobs:
  ops:
    # Only PR comments (issue_comment fires on issues too).
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-slim
    steps:
      - id: authz
        uses: ship-iac/shipmate/actions/comment-ops@dcd760e86a2d02ee7c2a0d3a9277d4da262a6dab
        with:
          app-id: ${{ vars.SHIPMATE_APP_ID }}
          private-key: ${{ secrets.SHIPMATE_APP_PRIVATE_KEY }}
          approvers-team: ${{ vars.SHIPMATE_APPROVERS_TEAM }}
          comment-body: ${{ github.event.comment.body }}
          comment-user: ${{ github.event.comment.user.login }}
          comment-id: ${{ github.event.comment.id }}
          pr-number: ${{ github.event.issue.number }}
          github-token: ${{ github.token }}
      - if: ${{ steps.authz.outputs.authorized == 'true' }}
        uses: ship-iac/shipmate/actions/dispatch@dcd760e86a2d02ee7c2a0d3a9277d4da262a6dab
        with:
          app-id: ${{ vars.SHIPMATE_APP_ID }}
          private-key: ${{ secrets.SHIPMATE_APP_PRIVATE_KEY }}
          environment: ${{ steps.authz.outputs.environment }}
          ref: ${{ steps.authz.outputs.head-sha }}
          pr-number: ${{ github.event.issue.number }}
          plan-run-id: ${{ steps.authz.outputs.plan-run-id }}
          dispatch-ref: ${{ github.event.repository.default_branch }}
          repository: ${{ github.repository }}
