name: deploy
on:
  push:
    branches: [main]
concurrency:
  group: deploy-main
  cancel-in-progress: false
permissions:
  contents: read
  checks: write
  pull-requests: read
  actions: read
jobs:
  deploy:
    uses: ship-iac/shipmate/.github/workflows/deploy.yml@74a0e452fb01577d8b61f8589b2a09b0c8112b7f
    permissions: { contents: read, checks: write, pull-requests: read, actions: read }
    secrets: inherit
    with:
      state_suffix: terraform.tfstate
