name: deploy
on:
  push:
    branches: [main]
concurrency:
  group: deploy-main
  cancel-in-progress: false
permissions:
  contents: read
  checks: write
  pull-requests: read
  actions: read
jobs:
  deploy:
    uses: ship-iac/shipmate/.github/workflows/deploy.yml@3cea4b54ce6f378ca29727fc5daa6eb9db0e43e5
    permissions: { contents: read, checks: write, pull-requests: read, actions: read }
    secrets: inherit
    with:
      state_suffix: terraform.tfstate
