name: deploy
on:
  push:
    branches: [main]
concurrency:
  group: deploy-main
  cancel-in-progress: false
permissions:
  contents: read
  pull-requests: read
  actions: read
jobs:
  deploy:
    uses: ship-iac/shipmate/.github/workflows/deploy.yml@2868122c6b372146e0879556e3dcb9f226265f6b
    permissions: { contents: read, checks: read, pull-requests: read, actions: read }
    secrets: inherit
    with:
      state_suffix: terraform.tfstate
